.PHONY: eks_up eks_down server_build eks_cluster_up eks_cluster_down eks_cluster_add_nodes eks_cluster_set_up eks_cluster_kubernetes_dashboard_up eks_cluster_kubernetes_dashboard_down eks_cluster_demo_application_up eks_cluster_demo_application_down eks_cluster_kubernetes_metric_service_up eks_cluster_kubernetes_metric_service_down edit_secret_vars

all: cd ansible

eks_up eks_down server_build eks_cluster_up eks_cluster_down eks_cluster_add_nodes eks_cluster_set_up eks_cluster_kubernetes_dashboard_up eks_cluster_kubernetes_dashboard_down eks_cluster_demo_application_up eks_cluster_demo_application_down eks_cluster_kubernetes_metric_service_up eks_cluster_kubernetes_metric_service_down edit_secret_vars:
	cd ansible ; \
	make $@ ; \
	cd ..	