---
- name: Creates the applications namespace
  hosts: local
  connection: local
  gather_facts: no
  tags:
    - kubernetes
  vars_files:
    - ./secret.yml
  tasks:
    - name: Applies the Namespace definition
      k8s:
        state: '{{ applications_namespace_state }}'
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: '{{ applications_namespace_name }}'
