---
- name: Run a DEMO application on the cluster
  hosts: local
  connection: local
  gather_facts: no
  tags:
    - shell
  tasks:
    - name: Apply the ecsdemo-nodejs deployment file
      shell: 'kubectl apply -f ../eks/ecsdemo-nodejs/deployment.yaml'
    - name: Apply the ecsdemo-nodejs service file
      shell: 'kubectl apply -f ../eks/ecsdemo-nodejs/service.yaml'
    - name: Apply the ecsdemo-crystal deployment file
      shell: 'kubectl apply -f ../eks/ecsdemo-crystal/deployment.yaml'
    - name: Apply the ecsdemo-crystal service file
      shell: 'kubectl apply -f ../eks/ecsdemo-crystal/service.yaml'
    - name: Apply the ecsdemo-frontend deployment file
      shell: 'kubectl apply -f ../eks/ecsdemo-frontend/deployment.yaml'
    - name: Apply the ecsdemo-frontend service file
      shell: 'kubectl apply -f ../eks/ecsdemo-frontend/service.yaml'
    - name: Apply the ecsdemo-frontend ingress file
      shell: 'kubectl apply -f ../eks/ecsdemo-frontend/ingress.yaml'
