---
- name: Crear los templates
  hosts: local
  connection: local
  gather_facts: no
  tags:
    - templates
  vars_files:
    - ../cloudformation/output.yaml
  tasks:
    - set_fact:
        eks_cluster_node_instance_role_arn: '{{ stack_outputs["EKSClusterNodeInstanceRoleArn"] }}'
    - name: Create the aws_auth_cm.yaml file
      template:
        src: './templates/aws_auth_cm.yaml'
        dest: '../eks/aws_auth_cm.yaml'
    - name: Add nodes to the cluster
      shell: 'kubectl create -f ../eks/aws_auth_cm.yaml'