---
- name: Crear los templates
  hosts: local
  connection: local
  gather_facts: no
  tags:
    - templates
  vars_files:
    - ./secret.yml
  tasks:
    - name: Create the eks_cluster_template.yml file
      template:
        src: './templates/eks_cluster_template.yml'
        dest: '../cloudformation/eks_cluster_template.yml'

- name: Crear/Destruir el cluster de EKS con CloudFormation
  hosts: local
  connection: local
  gather_facts: no
  tags:
    - cloudformation
  vars_files:
    - ./secret.yml
  tasks:
    - name: Correr el template de Cloudformation
      cloudformation:
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        region: 'us-east-1'
        stack_name: '{{ eks_cluster_name }}'
        state: '{{ eks_cluster_state }}'
        template: '../cloudformation/eks_cluster_template.yml'
        disable_rollback: true
        tags:
          Name: '{{ eks_cluster_name }}'
          Project: '{{ eks_cluster_name }}'
      register: output
    - name: Guardar salida
      copy:
        content: '{{ output | to_nice_yaml }}'
        dest: '../cloudformation/output.yaml'