---
- name: Crear los templates
  hosts: local
  connection: local
  gather_facts: no
  tags:
    - templates
  vars_files:
    - ../cloudformation/output.yaml
    - ./secret.yml
  tasks:
    - set_fact:
        eks_cluster_node_instance_role_arn: '{{ stack_outputs["EKSClusterNodeInstanceRoleArn"] }}'
        eks_cluster_admin_instance_role_arn: '{{ stack_outputs["EKSClusterAdminInstanceNodeArn"] }}'
    - name: Add nodes to the cluster
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: aws-auth
            namespace: kube-system
          data:
            mapRoles: |
              - rolearn: '{{ eks_cluster_node_instance_role_arn }}'
                username: 'system:node:{% raw %}{{EC2PrivateDNSName}}{% endraw %}'
                groups:
                  - system:bootstrappers
                  - system:nodes
              - rolearn: '{{ eks_cluster_admin_instance_role_arn }}'
                username: cluster-admin
                groups:
                  - system:masters
    - name: Get cluster info
      k8s_facts:
        api_version: v1
        kind: nodes